version: '3.8'
services:
    jms:
        image: vromero/activemq-artemis
        ports:
          - 8161:8161
          - 61616:61616
    zipkin:
        image: openzipkin/zipkin
        ports:
          - 9411:9411
    eureka:
        image: frigir/mssc-brewery-eureka
        ports:
          - 8761:8761
    config:
        image: frigir/mssc-brewery-config-server
        ports:
          - 8888:8888
        depends_on:
          - eureka
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
    inventory:
        image: frigir/mssc-beer-inventory-service
        ports:
          - 8082:8082
        depends_on:
          - eureka
          - config
          - jms
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
          SPRING_PROFILES_ACTIVE: local-discovery,localmysql
          SPRING_ZIPKIN_BASEURL: http://zipkin
          SPRING_ARTEMIS_HOST: jms
          SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerinventoryservice?userUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
          SPRING_CLOUD_CONFIG_URI: http://config:8888
    beer:
        image: frigir/mssc-beer-service
        ports:
          - 8080:808
        depends_on:
          - inventory
          - eureka
          - config
          - jms
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
          SPRING_PROFILES_ACTIVE: local-discovery,localmysql
          SPRING_ZIPKIN_BASEURL: http://zipkin
          SPRING_ARTEMIS_HOST: jms
          SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerservice?userUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
          SPRING_CLOUD_CONFIG_URI: http://config:8888
    order:
        image: frigir/mssc-beer-order-service
        ports:
          - 8081:8081
        depends_on:
          - eureka
          - config
          - jms
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
          SPRING_PROFILES_ACTIVE: local-discovery,localmysql
          SPRING_ZIPKIN_BASEURL: http://zipkin
          SPRING_ARTEMIS_HOST: jms
          SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerorderservice?userUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
          SFG_BREWERY_BEERSERVICEHOST: http://beer:8080/beer/
          SPRING_CLOUD_CONFIG_URI: http://config:8888
    inventory-failover:
        image: frigir/mssc-beer-inventory-failover-service
        ports:
          - 8083:8083
        depends_on:
          - eureka
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
          SPRING_PROFILES_ACTIVE: local-discovery
          SPRING_ZIPKIN_BASEURL: http://zipkin
    gateway:
        image: frigir/mssc-brewery-gateway
        ports:
          - 9090:9090
        depends_on:
          - eureka
          - inventory
          - beer
          - inventory-failover
          - order
          - config
        environment:
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
          SPRING_PROFILES_ACTIVE: local-discovery